var b;b||=typeof Module != 'undefined' ? Module : {};var g=Object.assign({},b),t="",v,w;t=self.location.href;t=t.startsWith("blob:")?"":t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1);w=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)};v=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var x=b.printErr||console.error.bind(console);
Object.assign(b,g);g=null;var y=b.wasmBinary,z,A=!1,B,C,D,E,F,I;function J(){var a=z.buffer;b.HEAP8=C=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAPU8=D=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAP32=E=new Int32Array(a);b.HEAPU32=F=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=I=new Float64Array(a)}var K=[],L=[],aa=[],ba=[];function ca(){var a=b.preRun.shift();K.unshift(a)}var M=0,N=null;
function da(a){b.onAbort?.(a);a="Aborted("+a+")";x(a);A=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ea=a=>a.startsWith("data:application/octet-stream;base64,"),O;async function fa(a){if(!y)try{var c=await v(a);return new Uint8Array(c)}catch{}if(a==O&&y)a=new Uint8Array(y);else if(w)a=w(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ha(a,c){try{var d=await fa(a);return await WebAssembly.instantiate(d,c)}catch(e){x(`failed to asynchronously prepare wasm: ${e}`),da(e)}}async function ia(a){var c=O;if(!y&&"function"==typeof WebAssembly.instantiateStreaming&&!ea(c)&&"function"==typeof fetch)try{var d=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(e){x(`wasm streaming compile failed: ${e}`),x("falling back to ArrayBuffer instantiation")}return ha(c,a)}
var ma={8724:()=>{console.info("WASM Initialised, ready to trace.");ja=!0;for(const a of ka)la(a)}};class na{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var P=a=>{for(;0<a.length;)a.shift()(b)},Q=b.noExitRuntime||!0,R=0,S={},T=a=>{if(!(a instanceof na||"unwind"==a))throw a;},U=a=>{B=a;Q||0<R||(b.onExit?.(a),A=!0);throw new na(a);},oa=a=>{if(!A)try{if(a(),!(Q||0<R))try{B=a=B,U(a)}catch(c){T(c)}}catch(c){T(c)}},V=[],pa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,qa=(a=0)=>{for(var c=D,d=a+NaN,e=a;c[e]&&!(e>=d);)++e;if(16<e-a&&c.buffer&&pa)return pa.decode(c.subarray(a,e));for(d="";a<e;){var f=c[a++];if(f&128){var l=c[a++]&63;if(192==(f&224))d+=
String.fromCharCode((f&31)<<6|l);else{var q=c[a++]&63;f=224==(f&240)?(f&15)<<12|l<<6|q:(f&7)<<18|l<<12|q<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},ta=(a,c,d,e)=>{var f={string:k=>{var n=0;if(null!==k&&void 0!==k&&0!==k){for(var h=n=0;h<k.length;++h){var p=k.charCodeAt(h);127>=p?n++:2047>=p?n+=2:55296<=p&&57343>=p?(n+=4,++h):n+=3}var u=n+1;h=n=W(u);p=D;if(0<u){u=h+u-1;for(var G=0;G<k.length;++G){var m=
k.charCodeAt(G);if(55296<=m&&57343>=m){var xa=k.charCodeAt(++G);m=65536+((m&1023)<<10)|xa&1023}if(127>=m){if(h>=u)break;p[h++]=m}else{if(2047>=m){if(h+1>=u)break;p[h++]=192|m>>6}else{if(65535>=m){if(h+2>=u)break;p[h++]=224|m>>12}else{if(h+3>=u)break;p[h++]=240|m>>18;p[h++]=128|m>>12&63}p[h++]=128|m>>6&63}p[h++]=128|m&63}}p[h]=0}}return n},array:k=>{var n=W(k.length);C.set(k,n);return n}};a=b["_"+a];var l=[],q=0;if(e)for(var r=0;r<e.length;r++){var H=f[d[r]];H?(0===q&&(q=ra()),l[r]=H(e[r])):l[r]=e[r]}d=
a(...l);return d=function(k){0!==q&&sa(q);return"string"===c?k?qa(k):"":"boolean"===c?!!k:k}(d)},va={f:()=>da(""),e:(a,c,d)=>D.copyWithin(a,c,c+d),b:()=>{Q=!1;R=0},c:(a,c)=>{S[a]&&(clearTimeout(S[a].id),delete S[a]);if(!c)return 0;var d=setTimeout(()=>{delete S[a];oa(()=>ua(a,performance.now()))},c);S[a]={id:d,C:c};return 0},g:(a,c,d)=>{V.length=0;for(var e;e=D[c++];){var f=105!=e;f&=112!=e;d+=f&&d%8?4:0;V.push(112==e?F[d>>2]:105==e?E[d>>2]:I[d>>3]);d+=f?8:4}return ma[a](...V)},d:a=>{var c=D.length;
a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=c*(1+.2/d);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-z.buffer.byteLength+65535)/65536|0;try{z.grow(e);J();var f=1;break a}catch(l){}f=void 0}if(f)return!0}return!1},a:U},X;
(async function(){function a(d){X=d.exports;z=X.h;J();L.unshift(X.i);M--;b.monitorRunDependencies?.(M);0==M&&N&&(d=N,N=null,d());return X}M++;b.monitorRunDependencies?.(M);var c={a:va};if(b.instantiateWasm)try{return b.instantiateWasm(c,a)}catch(d){return x(`Module.instantiateWasm callback failed with error: ${d}`),!1}O??=ea("a.out.wasm")?"a.out.wasm":b.locateFile?b.locateFile("a.out.wasm",t):t+"a.out.wasm";c=await ia(c);a(c.instance);return c})();
b._create_buffer=(a,c)=>(b._create_buffer=X.j)(a,c);b._setCurrent=a=>(b._setCurrent=X.k)(a);b._addImage=(a,c,d,e)=>(b._addImage=X.l)(a,c,d,e);b._removeImage=a=>(b._removeImage=X.m)(a);b._historyStatus=()=>(b._historyStatus=X.n)();b._trace=(a,c,d)=>(b._trace=X.o)(a,c,d);b._undo=()=>(b._undo=X.p)();b._redo=()=>(b._redo=X.q)();b._clear=()=>(b._clear=X.r)();b._point=(a,c)=>(b._point=X.s)(a,c);b._autoTrace=a=>(b._autoTrace=X.t)(a);b._eraseRegion=(a,c)=>(b._eraseRegion=X.u)(a,c);
b._smoothTrace=()=>(b._smoothTrace=X.v)();b._exportTrace=(a,c,d,e,f,l,q,r,H,k,n,h)=>(b._exportTrace=X.w)(a,c,d,e,f,l,q,r,H,k,n,h);b._snap=(a,c,d)=>(b._snap=X.x)(a,c,d);b._getPixelColour=(a,c)=>(b._getPixelColour=X.y)(a,c);b._getCurrentPath=()=>(b._getCurrentPath=X.z)();var wa=b._main=(a,c)=>(wa=b._main=X.A)(a,c),ua=(a,c)=>(ua=X.B)(a,c),sa=a=>(sa=X.D)(a),W=a=>(W=X.E)(a),ra=()=>(ra=X.F)();
b.cwrap=(a,c,d,e)=>{var f=!d||d.every(l=>"number"===l||"boolean"===l);return"string"!==c&&f&&!e?b["_"+a]:(...l)=>ta(a,c,d,l)};var Y;N=function ya(){Y||za();Y||(N=ya)};
function za(){function a(){if(!Y&&(Y=!0,b.calledRun=!0,!A)){P(L);P(aa);b.onRuntimeInitialized?.();if(Aa){var c=wa;try{var d=c(0,0);B=d;U(d)}catch(e){T(e)}}if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;)c=b.postRun.shift(),ba.unshift(c);P(ba)}}if(!(0<M)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)ca();P(K);0<M||(b.setStatus?(b.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>b.setStatus(""),1);a()},1)):a())}}
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();var Aa=!0;b.noInitialRun&&(Aa=!1);za();
var Ba=b.cwrap("create_buffer","number",["number","number"]),Ca=b.cwrap("setCurrent","",["string"]),Da=b.cwrap("addImage","",["string","number","number","number"]),Ea=b.cwrap("removeImage","",["string"]),Fa=b.cwrap("historyStatus","number"),Ga=b.cwrap("trace","string",["number","number","number"]),Ha=b.cwrap("point","string",["number","number"]),Ia=b.cwrap("undo","string"),Ja=b.cwrap("redo","string"),Ka=b.cwrap("eraseRegion","string",["number","number"]),La=b.cwrap("smoothTrace","string"),Ma=b.cwrap("clear",
""),Na=b.cwrap("autoTrace","string",["number"]),Oa=b.cwrap("exportTrace","string",Array(12).fill("number")),Pa=b.cwrap("snap","number",["number","number","number"]),Qa=b.cwrap("getPixelColour","number",["number","number"]),Ra=b.cwrap("getCurrentPath","string");
const Z=(a,c)=>{a.svg=c;return a},Sa={setCurrent:a=>Ca(a.src),removeImage:a=>Ea(a.src),setData:a=>{const c=Ba(parseInt(a.width,10),parseInt(a.height,10));b.HEAPU8.set(a.data,c);Da(a.src,c,parseInt(a.width,10),parseInt(a.height,10));return{src:a.src,type:a.type}},getHistoryStatus:a=>{const c=Fa();a.undo=!!((c&2)>>1);a.redo=!!(c&1);return a},clearTrace:a=>Z(a,Ma()),undoTrace:a=>Z(a,Ia()),redoTrace:a=>Z(a,Ja()),eraseRegion:a=>Z(a,Ka(parseInt(a.begin,10),parseInt(a.end,10))),smoothTrace:a=>Z(a,La()),
exportTrace:a=>{a["export"]=Oa(parseInt(a.PPO,10),"tab"===a.delim?1:0,parseFloat(a.lowFR),parseFloat(a.highFR),parseFloat(a.SPL.top),parseFloat(a.SPL.topPixel),parseFloat(a.SPL.bottom),parseFloat(a.SPL.bottomPixel),parseFloat(a.FR.top),parseFloat(a.FR.topPixel),parseFloat(a.FR.bottom),parseFloat(a.FR.bottomPixel));return a},addPoint:a=>Z(a,Ha(parseInt(a.x,10),parseInt(a.y,10))),autoTrace:a=>Z(a,Na(parseInt(a.colourTolerance,10))),trace:a=>Z(a,Ga(parseInt(a.x,10),parseInt(a.y,10),parseInt(a.colourTolerance,
10))),snapLine:a=>{a.line.position=Pa(parseInt(a.line.position),"x"===a.line.direction?1:0,parseInt(a.direction,10));return a},getPixelColour:a=>{const c=Qa(parseInt(a.x,10),parseInt(a.y,10));a.pixelColour=`${c>>16}, ${c>>8&255}, ${c&255}`;return a},getCurrentPath:a=>Z(a,Ra())};let ja=!1;
const ka=[],la=a=>{if(ja){a=a.data;let c;try{c=Sa[a.type](a)}catch(d){console.error(d.message),c={type:"error",message:"Out of memory, please refresh the site. (You must have loaded a LOT of images at once)"}}c&&postMessage(c)}else ka.push(a)};self.onmessage=la;
