var c;c||=typeof Module != 'undefined' ? Module : {};const r=[];self.onmessage=a=>r.push(a);
c.onRuntimeInitialized=()=>{const a=TextDecoder.prototype.decode.bind(new TextDecoder("utf-8"));var d=b=>(...e)=>{e=b(...e);const m=a(new Uint8Array(u.buffer,w[e/4],w[e/4+1]));c._clean_string(e);return m};const g=new Map,f={F:c._create_buffer,O:b=>c._setCurrent(g.get(b)),C:(b,e,m,p)=>g.set(b,c._addImage(e,m,p)),N:b=>{c._removeImage(g.get(b));g.delete(b)},J:c._historyStatus,R:d(c._trace),L:d(c._point),S:d(c._undo),M:d(c._redo),H:d(c._eraseRegion),smooth:d(c._smoothTrace),clear:c._clear,D:d(c._autoTrace),
I:d(c._exportTrace),P:c._snap,K:c._getPixelColour,G:d(c._getCurrentPath)},k=(b,e)=>{b.svg=e;return b},v={setCurrent:({src:b})=>f.O(b),removeImage:({src:b})=>f.N(b),setData:({src:b,type:e,width:m,height:p,data:h})=>{const t=f.F(parseInt(m,10),parseInt(p,10));u.set(h,t);f.C(b,t,parseInt(m,10),parseInt(p,10));return{src:b,type:e}},getHistoryStatus:b=>{const e=f.J();b.undo=!!((e&2)>>1);b.redo=!!(e&1);return b},clearTrace:b=>k(b,f.clear()),undoTrace:b=>k(b,f.S()),redoTrace:b=>k(b,f.M()),eraseRegion:b=>
k(b,f.H(parseInt(b.begin,10),parseInt(b.end,10))),smoothTrace:b=>k(b,f.smooth()),exportTrace:b=>{b["export"]=f.I(parseInt(b.PPO,10),"tab"===b.delim?1:0,parseFloat(b.lowFR),parseFloat(b.highFR),parseFloat(b.SPL.top),parseFloat(b.SPL.topPixel),parseFloat(b.SPL.bottom),parseFloat(b.SPL.bottomPixel),parseFloat(b.FR.top),parseFloat(b.FR.topPixel),parseFloat(b.FR.bottom),parseFloat(b.FR.bottomPixel));return b},addPoint:b=>k(b,f.L(parseInt(b.x,10),parseInt(b.y,10))),autoTrace:b=>k(b,f.D(parseInt(b.colourTolerance,
10))),trace:b=>k(b,f.R(parseInt(b.x,10),parseInt(b.y,10),parseInt(b.colourTolerance,10))),snapLine:b=>{b.line.position=f.P(parseInt(b.line.position,10),"x"===b.line.direction?1:0,parseInt(b.direction,10));return b},getPixelColour:b=>{const e=f.K(parseInt(b.x,10),parseInt(b.y,10));b.pixelColour=`${e>>16}, ${e>>8&255}, ${e&255}`;return b},getCurrentPath:b=>k(b,f.G())};d=({data:b})=>{let e;try{e=v[b.type](b)}catch(m){console.error(m.message),e={type:"error",message:"Out of memory, please refresh the site. (You must have loaded a LOT of images at once)"}}e&&
postMessage(e)};self.onmessage=d;for(const b of r)d(b);r.length=0};var x;x=self.location.href;var y="",z,B;try{y=(new URL(".",x)).href}catch{}B=a=>{var d=new XMLHttpRequest;d.open("GET",a,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)};z=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var C=console.log.bind(console),D=console.error.bind(console),E=!1,F,u,w;
function H(){var a=F.buffer;new Int8Array(a);new Int16Array(a);u=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);w=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var I=0,J=null;function K(a){a="Aborted("+a+")";D(a);E=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var L;
async function M(a){try{var d=await z(a);return new Uint8Array(d)}catch{}if(B)a=B(a);else throw"both async and sync fetching of the wasm failed";return a}async function N(a,d){try{var g=await M(a);return await WebAssembly.instantiate(g,d)}catch(f){D(`failed to asynchronously prepare wasm: ${f}`),K(f)}}
async function O(a){var d=L;try{var g=fetch(d,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(g,a)}catch(f){D(`wasm streaming compile failed: ${f}`),D("falling back to ArrayBuffer instantiation")}return N(d,a)}class P{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Q={},S=a=>{if(!E)try{a()}catch(d){if(!(d instanceof P||"unwind"==d))throw d;}},T=[null,[],[]],U="undefined"!=typeof TextDecoder?new TextDecoder:void 0,V,W={f:()=>K(""),b:()=>{},c:(a,d)=>{Q[a]&&(clearTimeout(Q[a].id),delete Q[a]);if(!d)return 0;var g=setTimeout(()=>{delete Q[a];S(()=>V(a,performance.now()))},d);Q[a]={id:g,T:d};return 0},g:a=>{var d=u.length;a>>>=0;if(2147483648<a)return!1;for(var g=1;4>=g;g*=2){a:{var f=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d+50331648/g)/65536))-F.buffer.byteLength+
65535)/65536|0;try{F.grow(f);H();var k=1;break a}catch(v){}k=void 0}if(k)return!0}return!1},e:()=>52,d:(a,d,g,f)=>{for(var k=0,v=0;v<g;v++){var b=w[d>>2],e=w[d+4>>2];d+=8;for(var m=0;m<e;m++){var p=a,h=u[b+m],t=T[p];if(0===h||10===h){p=1===p?C:D;h=t;var q=0;var A=h;for(var n=q,l=n+void 0;A[n]&&!(n>=l);)++n;A=n;if(16<A-q&&h.buffer&&U)h=U.decode(h.subarray(q,A));else{for(n="";q<A;)if(l=h[q++],l&128){var G=h[q++]&63;if(192==(l&224))n+=String.fromCharCode((l&31)<<6|G);else{var R=h[q++]&63;l=224==(l&240)?
(l&15)<<12|G<<6|R:(l&7)<<18|G<<12|R<<6|h[q++]&63;65536>l?n+=String.fromCharCode(l):(l-=65536,n+=String.fromCharCode(55296|l>>10,56320|l&1023))}}else n+=String.fromCharCode(l);h=n}p(h);t.length=0}else t.push(h)}k+=e}w[f>>2]=k;return 0},a:a=>{throw new P(a);}},X;
(async function(){I++;var a={a:W};L??=y+"a.out.wasm";X=(await O(a)).instance.exports;F=X.h;H();a=X;c._clean_string=a.j;c._create_buffer=a.k;c._setCurrent=a.l;c._addImage=a.m;c._removeImage=a.n;c._historyStatus=a.o;c._trace=a.p;c._undo=a.q;c._redo=a.r;c._clear=a.s;c._point=a.t;c._autoTrace=a.u;c._eraseRegion=a.v;c._smoothTrace=a.w;c._exportTrace=a.x;c._snap=a.y;c._getPixelColour=a.z;c._getCurrentPath=a.A;V=a.B;I--;0==I&&J&&(a=J,J=null,a());return X})();
function Y(){0<I?J=Y:0<I?J=Y:(c.calledRun=!0,E||(X.i(),c.onRuntimeInitialized?.()))}Y();
