var Module;Module||=typeof Module != 'undefined' ? Module : {};var ENVIRONMENT_IS_WEB=!1,ENVIRONMENT_IS_WORKER=!0,moduleOverrides=Object.assign({},Module),arguments_=[],thisProgram="./this.program",quit_=(a,b)=>{throw b;},scriptDirectory="";function locateFile(a){return Module.locateFile?Module.locateFile(a,scriptDirectory):scriptDirectory+a}var readAsync,readBinary;
if(ENVIRONMENT_IS_WEB||ENVIRONMENT_IS_WORKER)ENVIRONMENT_IS_WORKER?scriptDirectory=self.location.href:"undefined"!=typeof document&&document.currentScript&&(scriptDirectory=document.currentScript.src),scriptDirectory=scriptDirectory.startsWith("blob:")?"":scriptDirectory.substr(0,scriptDirectory.replace(/[?#].*/,"").lastIndexOf("/")+1),ENVIRONMENT_IS_WORKER&&(readBinary=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),readAsync=
async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var out=Module.print||console.log.bind(console),err=Module.printErr||console.error.bind(console);Object.assign(Module,moduleOverrides);moduleOverrides=null;Module.arguments&&(arguments_=Module.arguments);Module.thisProgram&&(thisProgram=Module.thisProgram);var wasmBinary=Module.wasmBinary,wasmMemory,ABORT=!1,EXITSTATUS,HEAP8,HEAPU8,HEAP16,HEAPU16,HEAP32,HEAPU32,HEAPF32,HEAPF64;
function updateMemoryViews(){var a=wasmMemory.buffer;Module.HEAP8=HEAP8=new Int8Array(a);Module.HEAP16=HEAP16=new Int16Array(a);Module.HEAPU8=HEAPU8=new Uint8Array(a);Module.HEAPU16=HEAPU16=new Uint16Array(a);Module.HEAP32=HEAP32=new Int32Array(a);Module.HEAPU32=HEAPU32=new Uint32Array(a);Module.HEAPF32=HEAPF32=new Float32Array(a);Module.HEAPF64=HEAPF64=new Float64Array(a)}var __ATPRERUN__=[],__ATINIT__=[],__ATMAIN__=[],__ATPOSTRUN__=[],runtimeInitialized=!1;
function preRun(){if(Module.preRun)for("function"==typeof Module.preRun&&(Module.preRun=[Module.preRun]);Module.preRun.length;)addOnPreRun(Module.preRun.shift());callRuntimeCallbacks(__ATPRERUN__)}function initRuntime(){runtimeInitialized=!0;callRuntimeCallbacks(__ATINIT__)}function preMain(){callRuntimeCallbacks(__ATMAIN__)}
function postRun(){if(Module.postRun)for("function"==typeof Module.postRun&&(Module.postRun=[Module.postRun]);Module.postRun.length;)addOnPostRun(Module.postRun.shift());callRuntimeCallbacks(__ATPOSTRUN__)}function addOnPreRun(a){__ATPRERUN__.unshift(a)}function addOnInit(a){__ATINIT__.unshift(a)}function addOnPostRun(a){__ATPOSTRUN__.unshift(a)}var runDependencies=0,dependenciesFulfilled=null;function addRunDependency(a){runDependencies++;Module.monitorRunDependencies?.(runDependencies)}
function removeRunDependency(a){runDependencies--;Module.monitorRunDependencies?.(runDependencies);0==runDependencies&&dependenciesFulfilled&&(a=dependenciesFulfilled,dependenciesFulfilled=null,a())}function abort(a){Module.onAbort?.(a);a="Aborted("+a+")";err(a);ABORT=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var dataURIPrefix="data:application/octet-stream;base64,",isDataURI=a=>a.startsWith(dataURIPrefix);
function findWasmBinary(){return isDataURI("a.out.wasm")?"a.out.wasm":locateFile("a.out.wasm")}var wasmBinaryFile;function getBinarySync(a){if(a==wasmBinaryFile&&wasmBinary)return new Uint8Array(wasmBinary);if(readBinary)return readBinary(a);throw"both async and sync fetching of the wasm failed";}async function getWasmBinary(a){if(!wasmBinary)try{var b=await readAsync(a);return new Uint8Array(b)}catch{}return getBinarySync(a)}
async function instantiateArrayBuffer(a,b){try{var c=await getWasmBinary(a);return await WebAssembly.instantiate(c,b)}catch(d){err(`failed to asynchronously prepare wasm: ${d}`),abort(d)}}
async function instantiateAsync(a,b,c){if(!a&&"function"==typeof WebAssembly.instantiateStreaming&&!isDataURI(b)&&"function"==typeof fetch)try{var d=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,c)}catch(e){err(`wasm streaming compile failed: ${e}`),err("falling back to ArrayBuffer instantiation")}return instantiateArrayBuffer(b,c)}function getWasmImports(){return{a:wasmImports}}
async function createWasm(){function a(c,d){wasmExports=c.exports;wasmMemory=wasmExports.h;updateMemoryViews();addOnInit(wasmExports.i);removeRunDependency("wasm-instantiate");return wasmExports}addRunDependency("wasm-instantiate");var b=getWasmImports();if(Module.instantiateWasm)try{return Module.instantiateWasm(b,a)}catch(c){return err(`Module.instantiateWasm callback failed with error: ${c}`),!1}wasmBinaryFile??=findWasmBinary();b=await instantiateAsync(wasmBinary,wasmBinaryFile,b);a(b.instance);
return b}var ASM_CONSTS={8724:()=>{onLoad()}};class ExitStatus{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var callRuntimeCallbacks=a=>{for(;0<a.length;)a.shift()(Module)},noExitRuntime=Module.noExitRuntime||!0,stackRestore=a=>__emscripten_stack_restore(a),stackSave=()=>_emscripten_stack_get_current(),__abort_js=()=>abort(""),__emscripten_memcpy_js=(a,b,c)=>HEAPU8.copyWithin(a,b,b+c),runtimeKeepaliveCounter=0,__emscripten_runtime_keepalive_clear=()=>{noExitRuntime=!1;runtimeKeepaliveCounter=0},timers={},handleException=a=>{if(a instanceof ExitStatus||"unwind"==a)return EXITSTATUS;quit_(1,a)},keepRuntimeAlive=
()=>noExitRuntime||0<runtimeKeepaliveCounter,_proc_exit=a=>{EXITSTATUS=a;keepRuntimeAlive()||(Module.onExit?.(a),ABORT=!0);quit_(a,new ExitStatus(a))},exitJS=(a,b)=>{EXITSTATUS=a;_proc_exit(a)},_exit=exitJS,maybeExit=()=>{if(!keepRuntimeAlive())try{_exit(EXITSTATUS)}catch(a){handleException(a)}},callUserCallback=a=>{if(!ABORT)try{a(),maybeExit()}catch(b){handleException(b)}},_emscripten_get_now=()=>performance.now(),__setitimer_js=(a,b)=>{timers[a]&&(clearTimeout(timers[a].id),delete timers[a]);if(!b)return 0;
var c=setTimeout(()=>{delete timers[a];callUserCallback(()=>__emscripten_timeout(a,_emscripten_get_now()))},b);timers[a]={id:c,timeout_ms:b};return 0},readEmAsmArgsArray=[],readEmAsmArgs=(a,b)=>{readEmAsmArgsArray.length=0;for(var c;c=HEAPU8[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;readEmAsmArgsArray.push(112==c?HEAPU32[b>>2]:105==c?HEAP32[b>>2]:HEAPF64[b>>3]);b+=d?8:4}return readEmAsmArgsArray},runEmAsmFunction=(a,b,c)=>{b=readEmAsmArgs(b,c);return ASM_CONSTS[a](...b)},_emscripten_asm_const_int=
(a,b,c)=>runEmAsmFunction(a,b,c),getHeapMax=()=>2147483648,alignMemory=(a,b)=>Math.ceil(a/b)*b,growMemory=a=>{a=(a-wasmMemory.buffer.byteLength+65535)/65536|0;try{return wasmMemory.grow(a),updateMemoryViews(),1}catch(b){}},_emscripten_resize_heap=a=>{var b=HEAPU8.length;a>>>=0;var c=getHeapMax();if(a>c)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);e=Math.min(c,alignMemory(Math.max(a,e),65536));if(growMemory(e))return!0}return!1},getCFunc=a=>Module["_"+a],writeArrayToMemory=
(a,b)=>{HEAP8.set(a,b)},lengthBytesUTF8=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},stringToUTF8Array=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var k=a.charCodeAt(++g);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+
3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0;return c-e},stringToUTF8=(a,b,c)=>stringToUTF8Array(a,HEAPU8,b,c),stackAlloc=a=>__emscripten_stack_alloc(a),stringToUTF8OnStack=a=>{var b=lengthBytesUTF8(a)+1,c=stackAlloc(b);stringToUTF8(a,c,b);return c},UTF8Decoder="undefined"!=typeof TextDecoder?new TextDecoder:void 0,UTF8ArrayToString=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&UTF8Decoder)return UTF8Decoder.decode(a.subarray(b,
c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},UTF8ToString=(a,b)=>a?UTF8ArrayToString(HEAPU8,a,b):"",ccall=(a,b,c,d,e)=>{e={string:h=>{var l=0;null!==h&&void 0!==h&&0!==h&&(l=stringToUTF8OnStack(h));return l},array:h=>
{var l=stackAlloc(h.length);writeArrayToMemory(h,l);return l}};a=getCFunc(a);var g=[],f=0;if(d)for(var k=0;k<d.length;k++){var m=e[c[k]];m?(0===f&&(f=stackSave()),g[k]=m(d[k])):g[k]=d[k]}c=a(...g);return c=function(h){0!==f&&stackRestore(f);h="string"===b?UTF8ToString(h):"boolean"===b?!!h:h;return h}(c)},cwrap=(a,b,c,d)=>{var e=!c||c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&e&&!d?getCFunc(a):(...g)=>ccall(a,b,c,g,d)},wasmImports={f:__abort_js,e:__emscripten_memcpy_js,b:__emscripten_runtime_keepalive_clear,
c:__setitimer_js,g:_emscripten_asm_const_int,d:_emscripten_resize_heap,a:_proc_exit},wasmExports;createWasm();
var ___wasm_call_ctors=()=>(___wasm_call_ctors=wasmExports.i)(),_create_buffer=Module._create_buffer=(a,b)=>(_create_buffer=Module._create_buffer=wasmExports.j)(a,b),_setCurrent=Module._setCurrent=a=>(_setCurrent=Module._setCurrent=wasmExports.k)(a),_addImage=Module._addImage=(a,b,c,d)=>(_addImage=Module._addImage=wasmExports.l)(a,b,c,d),_removeImage=Module._removeImage=a=>(_removeImage=Module._removeImage=wasmExports.m)(a),_historyStatus=Module._historyStatus=()=>(_historyStatus=Module._historyStatus=
wasmExports.n)(),_trace=Module._trace=(a,b,c)=>(_trace=Module._trace=wasmExports.o)(a,b,c),_undo=Module._undo=()=>(_undo=Module._undo=wasmExports.p)(),_redo=Module._redo=()=>(_redo=Module._redo=wasmExports.q)(),_clear=Module._clear=()=>(_clear=Module._clear=wasmExports.r)(),_point=Module._point=(a,b)=>(_point=Module._point=wasmExports.s)(a,b),_autoTrace=Module._autoTrace=a=>(_autoTrace=Module._autoTrace=wasmExports.t)(a),_eraseRegion=Module._eraseRegion=(a,b)=>(_eraseRegion=Module._eraseRegion=wasmExports.u)(a,
b),_smoothTrace=Module._smoothTrace=()=>(_smoothTrace=Module._smoothTrace=wasmExports.v)(),_exportTrace=Module._exportTrace=(a,b,c,d,e,g,f,k,m,h,l,n)=>(_exportTrace=Module._exportTrace=wasmExports.w)(a,b,c,d,e,g,f,k,m,h,l,n),_snap=Module._snap=(a,b,c)=>(_snap=Module._snap=wasmExports.x)(a,b,c),_getPixelColour=Module._getPixelColour=(a,b)=>(_getPixelColour=Module._getPixelColour=wasmExports.y)(a,b),_getCurrentPath=Module._getCurrentPath=()=>(_getCurrentPath=Module._getCurrentPath=wasmExports.z)(),
_main=Module._main=(a,b)=>(_main=Module._main=wasmExports.A)(a,b),__emscripten_timeout=(a,b)=>(__emscripten_timeout=wasmExports.B)(a,b),__emscripten_stack_restore=a=>(__emscripten_stack_restore=wasmExports.D)(a),__emscripten_stack_alloc=a=>(__emscripten_stack_alloc=wasmExports.E)(a),_emscripten_stack_get_current=()=>(_emscripten_stack_get_current=wasmExports.F)();Module.cwrap=cwrap;var calledRun;dependenciesFulfilled=function runCaller(){calledRun||run();calledRun||(dependenciesFulfilled=runCaller)};
function callMain(){var a=_main;try{var b=a(0,0);exitJS(b,!0);return b}catch(c){return handleException(c)}}function run(){function a(){calledRun||(calledRun=!0,Module.calledRun=!0,ABORT||(initRuntime(),preMain(),Module.onRuntimeInitialized?.(),shouldRunNow&&callMain(),postRun()))}0<runDependencies||(preRun(),0<runDependencies||(Module.setStatus?(Module.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>Module.setStatus(""),1);a()},1)):a()))}
if(Module.preInit)for("function"==typeof Module.preInit&&(Module.preInit=[Module.preInit]);0<Module.preInit.length;)Module.preInit.pop()();var shouldRunNow=!0;Module.noInitialRun&&(shouldRunNow=!1);run();
const typeMap={setCurrent,removeImage,setData:addImage,getHistoryStatus,clearTrace:clear,undoTrace:undo,redoTrace:redo,eraseRegion,smoothTrace,exportTrace,addPoint:point,autoTrace:auto,trace,snapLine,getPixelColour,getCurrentPath},api={create_buffer:Module.cwrap("create_buffer","number",["number","number"]),setCurrent:Module.cwrap("setCurrent","",["string"]),addImage:Module.cwrap("addImage","",["string","number","number","number"]),removeImage:Module.cwrap("removeImage","",["string"]),historyStatus:Module.cwrap("historyStatus",
"number"),trace:Module.cwrap("trace","string",["number","number","number"]),point:Module.cwrap("point","string",["number","number"]),undo:Module.cwrap("undo","string"),redo:Module.cwrap("redo","string"),eraseRegion:Module.cwrap("eraseRegion","string",["number","number"]),smoothTrace:Module.cwrap("smoothTrace","string"),clear:Module.cwrap("clear",""),auto:Module.cwrap("autoTrace","string",["number"]),exportTrace:Module.cwrap("exportTrace","string","number number number number number number number number number number number number".split(" ")),
snap:Module.cwrap("snap","number",["number","number","number"]),getPixelColour:Module.cwrap("getPixelColour","number",["number","number"]),getCurrentPath:Module.cwrap("getCurrentPath","string")};let initialised=!1;const preInitQueue=[],messageListener=a=>{if(initialised){a=a.data;let b;try{b=typeMap[a.type](a)}catch(c){console.error(c.message),b={type:"error",message:"Out of memory, please refresh the site. (You must have loaded a LOT of images at once)"}}b&&postMessage(b)}else preInitQueue.push(a)};
function onLoad(){console.info("WASM Initialised, ready to trace.");initialised=!0;for(const a of preInitQueue)messageListener(a)}onmessage=messageListener;function setCurrent(a){api.setCurrent(a.src)}function addImage(a){const b=api.create_buffer(a.width,a.height);Module.HEAPU8.set(a.data,b);api.addImage(a.src,b,parseInt(a.width),parseInt(a.height));return{src:a.src,type:a.type}}function removeImage(a){api.removeImage(a.src)}
function getHistoryStatus(a){const b=api.historyStatus();a.undo=!!((b&2)>>1);a.redo=!!(b&1);return a}function trace(a){return defaultTraceResponse(a,api.trace(parseInt(a.x),parseInt(a.y),parseInt(a.colourTolerance)))}function point(a){return defaultTraceResponse(a,api.point(parseInt(a.x),parseInt(a.y)))}function auto(a){return defaultTraceResponse(a,api.auto(parseInt(a.colourTolerance)))}function undo(a){return defaultTraceResponse(a,api.undo())}
function redo(a){return defaultTraceResponse(a,api.redo())}function eraseRegion(a){return defaultTraceResponse(a,api.eraseRegion(parseInt(a.begin),parseInt(a.end)))}function smoothTrace(a){return defaultTraceResponse(a,api.smoothTrace())}function clear(a){return defaultTraceResponse(a,api.clear())}
function exportTrace(a){a.export=api.exportTrace(parseInt(a.PPO),"tab"===a.delim?1:0,parseFloat(a.lowFR),parseFloat(a.highFR),parseFloat(a.SPL.top),parseFloat(a.SPL.topPixel),parseFloat(a.SPL.bottom),parseFloat(a.SPL.bottomPixel),parseFloat(a.FR.top),parseFloat(a.FR.topPixel),parseFloat(a.FR.bottom),parseFloat(a.FR.bottomPixel));return a}function snapLine(a){a.line.position=api.snap(parseInt(a.line.position),"x"===a.line.direction?1:0,parseInt(a.direction));return a}
function getPixelColour(a){const b=api.getPixelColour(parseInt(a.x),parseInt(a.y));a.pixelColour=`${b>>16}, ${b>>8&255}, ${b&255}`;return a}function getCurrentPath(a){return defaultTraceResponse(a,api.getCurrentPath())}function defaultTraceResponse(a,b){a.svg=b;return a};
