var d;d||=typeof Module != 'undefined' ? Module : {};const m=[];self.onmessage=b=>m.push(b);const n=new Map;
d.onRuntimeInitialized=()=>{var b=TextDecoder.prototype.decode.bind(new TextDecoder("utf-8")),c=a=>(...f)=>(f=a(...f))?b(new Uint8Array(p.buffer,r[f/4],r[f/4+1])):"",g=0,h=new Map,e={F:d._create_buffer,O:a=>d._setCurrent(h.get(a)),C:(a,f,l,q)=>{n.set(++g,a);f=d._addImage(f,l,q,g);h.set(a,f)},N:a=>{var f=h.get(a);d._removeImage(f);h.delete(a)},J:d._historyStatus,R:c(d._trace),offsetTrace:c(d._offsetTrace),L:c(d._point),S:c(d._undo),M:c(d._redo),H:c(d._eraseRegion),smooth:c(d._smoothTrace),clear:d._clear,
D:c(d._autoTrace),I:c(d._exportTrace),P:d._snap,K:d._getPixelColour,G:c(d._getCurrentPath)},k=(a,f)=>{a.svg=f;return a},P={setCurrent:({src:a})=>e.O(a),removeImage:({src:a})=>e.N(a),setData:({src:a,type:f,width:l,height:q,data:N,image_id:O})=>{var B=e.F(parseInt(l,10),parseInt(q,10));p.set(N,B);e.C(a,B,parseInt(l,10),parseInt(q,10));return{src:a,type:f,image_id:O}},needsInverse:a=>{a.inverse=e.T(a.src);return a},getHistoryStatus:a=>{var f=e.J();a.undo=!!((f&2)>>1);a.redo=!!(f&1);return a},clearTrace:a=>
k(a,e.clear()),undoTrace:a=>k(a,e.S()),redoTrace:a=>k(a,e.M()),eraseRegion:a=>k(a,e.H(parseInt(a.begin,10),parseInt(a.end,10))),smoothTrace:a=>k(a,e.smooth()),exportTrace:a=>{a["export"]=e.I(parseInt(a.PPO,10),a.delim==="tab"?1:0,parseFloat(a.lowFR),parseFloat(a.highFR),parseFloat(a.SPL.top),parseFloat(a.SPL.topPixel),parseFloat(a.SPL.bottom),parseFloat(a.SPL.bottomPixel),parseFloat(a.FR.top),parseFloat(a.FR.topPixel),parseFloat(a.FR.bottom),parseFloat(a.FR.bottomPixel));return a},addPoint:a=>k(a,
e.L(parseInt(a.x,10),parseInt(a.y,10))),autoTrace:a=>k(a,e.D(a.colourTolerance,a.traceAlgorithm)),trace:a=>k(a,e.R(parseInt(a.x,10),parseInt(a.y,10),a.colourTolerance,a.traceAlgorithm)),offsetTrace:a=>k(a,e.offsetTrace(parseInt(a.direction,10),parseInt(a.magnitude,10))),snapLine:a=>{a.line.position=e.P(parseInt(a.line.position,10),a.line.direction==="x"?1:0,parseInt(a.direction,10));return a},getPixelColour:a=>{var f=e.K(parseInt(a.x,10),parseInt(a.y,10));a.pixelColour=`${f>>16}, ${f>>8&255}, ${f&
255}`;return a},getCurrentPath:a=>k(a,e.G())};c=({data:a})=>{try{var f=P[a.type](a)}catch(l){console.error(l.message),f={type:"error",message:"Out of memory, please refresh the site. (You must have loaded a LOT of images at once)"}}f&&postMessage(f)};self.onmessage=c;for(let a of m)c(a);m.length=0};var t;t=self.location.href;var u="",v,w;try{u=(new URL(".",t)).href}catch{}w=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)};
v=async b=>{b=await fetch(b,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);};var x=console.error.bind(console),y=!1;function z(){if(!A?.buffer?.resizable){var b=C.buffer;A=new Int8Array(b);p=new Uint8Array(b);D=new Int32Array(b);r=new Uint32Array(b);E=new Float64Array(b);F=new BigInt64Array(b)}}function G(b){b=`Aborted(${b})`;x(b);y=!0;throw new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");}var H;
async function I(b){try{var c=await v(b);return new Uint8Array(c)}catch{}if(w)b=w(b);else throw"both async and sync fetching of the wasm failed";return b}async function J(b,c){try{var g=await I(b);return await WebAssembly.instantiate(g,c)}catch(h){x(`failed to asynchronously prepare wasm: ${h}`),G(h)}}
async function K(b){var c=H;try{var g=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(g,b)}catch(h){x(`wasm streaming compile failed: ${h}`),x("falling back to ArrayBuffer instantiation")}return J(c,b)}class L{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}
var A,M={},Q=b=>{if(!y)try{b()}catch(c){if(!(c instanceof L||c=="unwind"))throw c;}finally{}},F,R=[],p,D,r,E,S={8872:(b,c)=>{var g=n.get(b);g&&(n.delete(b),postMessage({type:"needsInverse",src:g,inverse:c}))}},T,C,U={f:()=>G(""),c:()=>{},a:(b,c)=>{M[b]&&(clearTimeout(M[b].id),delete M[b]);if(!c)return 0;var g=setTimeout(()=>{delete M[b];Q(()=>T(b,performance.now()))},c);M[b]={id:g,U:c};return 0},e:function(b,c,g){if(!(b>=0&&b<=3))return 28;F[g>>3]=BigInt(Math.round((b===0?Date.now():performance.now())*
1E3*1E3));return 0},g:(b,c,g)=>{R.length=0;for(var h;h=p[c++];){var e=h!=105;e&=h!=112;g+=e&&g%8?4:0;R.push(h==112?r[g>>2]:h==106?F[g>>3]:h==105?D[g>>2]:E[g>>3]);g+=e?8:4}return S[b](...R)},d:b=>{var c=p.length;b>>>=0;if(b>2147483648)return!1;for(var g=1;g<=4;g*=2){a:{var h=(Math.min(2147483648,Math.ceil(Math.max(b,c+50331648/g)/65536)*65536)-C.buffer.byteLength+65535)/65536|0;try{C.grow(h);z();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},b:b=>{throw new L(b);}},V;
(async function(){var b={a:U};H??=u+"usytrace.wasm";b=V=(await K(b)).instance.exports;d._create_buffer=b.j;d._setCurrent=b.k;d._addImage=b.l;d._removeImage=b.m;d._historyStatus=b.n;d._trace=b.o;d._undo=b.p;d._redo=b.q;d._clear=b.r;d._point=b.s;d._autoTrace=b.t;d._eraseRegion=b.u;d._smoothTrace=b.v;d._offsetTrace=b.w;d._exportTrace=b.x;d._snap=b.y;d._getPixelColour=b.z;d._getCurrentPath=b.A;T=b.B;C=b.h;z();return V})().then(()=>{y||(V.i(),d.onRuntimeInitialized?.())});
