var d;d||=typeof Module != 'undefined' ? Module : {};const n=[];self.onmessage=b=>n.push(b);const p=new Map;
d.onRuntimeInitialized=()=>{var b=TextDecoder.prototype.decode.bind(new TextDecoder("utf-8")),c=a=>(...e)=>(e=a(...e))?b(new Uint8Array(q.buffer,r[e/4],r[e/4+1])):"",g=0,h=new Map,f={F:d._create_buffer,O:a=>d._setCurrent(h.get(a)),C:(a,e,l,m)=>{p.set(++g,a);e=d._addImage(e,l,m,g);h.set(a,e)},N:a=>{var e=h.get(a);d._removeImage(e);h.delete(a)},J:d._historyStatus,R:c(d._trace),offsetTrace:c(d._offsetTrace),L:c(d._point),S:c(d._undo),M:c(d._redo),H:c(d._eraseRegion),smooth:c(d._smoothTrace),clear:d._clear,
D:c(d._autoTrace),I:c(d._exportTrace),P:d._snap,K:d._getPixelColour,G:c(d._getCurrentPath)},k=(a,e)=>{a.svg=e;return a},P={setCurrent:({src:a})=>f.O(a),removeImage:({src:a})=>f.N(a),setData:({src:a,type:e,width:l,height:m,data:D,image_id:w})=>{l=parseInt(l,10);m=parseInt(m,10);if(!l||!m||l<3||m<3||!D)return{src:a,type:e,image_id:w,error:"Invalid image dimensions"};var x=f.F(l,m);if(!x)return{src:a,type:e,image_id:w,error:"Failed to allocate image buffer"};q.set(D,x);f.C(a,x,l,m);return{src:a,type:e,
image_id:w}},needsInverse:a=>{a.inverse=f.T(a.src);return a},getHistoryStatus:a=>{var e=f.J();a.undo=!!((e&2)>>1);a.redo=!!(e&1);return a},clearTrace:a=>k(a,f.clear()),undoTrace:a=>k(a,f.S()),redoTrace:a=>k(a,f.M()),eraseRegion:a=>k(a,f.H(parseInt(a.begin,10),parseInt(a.end,10))),smoothTrace:a=>k(a,f.smooth()),exportTrace:a=>{a["export"]=f.I(parseInt(a.PPO,10),a.delim==="tab"?1:0,parseInt(a.inputCompensation,10),parseFloat(a.lowFR),parseFloat(a.highFR),parseFloat(a.SPL.top),parseFloat(a.SPL.topPixel),
parseFloat(a.SPL.bottom),parseFloat(a.SPL.bottomPixel),parseFloat(a.FR.top),parseFloat(a.FR.topPixel),parseFloat(a.FR.bottom),parseFloat(a.FR.bottomPixel));return a},addPoint:a=>k(a,f.L(parseInt(a.x,10),parseInt(a.y,10))),autoTrace:a=>k(a,f.D(a.colourTolerance)),trace:a=>k(a,f.R(parseInt(a.x,10),parseInt(a.y,10),a.colourTolerance,a.traceAlgorithm)),offsetTrace:a=>k(a,f.offsetTrace(parseInt(a.direction,10),parseInt(a.magnitude,10))),snapLine:a=>{a.line.position=f.P(parseInt(a.line.position,10),a.line.direction===
"x"?1:0,parseInt(a.direction,10));return a},getPixelColour:a=>{var e=f.K(parseInt(a.x,10),parseInt(a.y,10));a.pixelColour=`${e>>16}, ${e>>8&255}, ${e&255}`;return a},getCurrentPath:a=>k(a,f.G())};c=({data:a})=>{try{var e=P[a.type](a)}catch(l){console.error(l.message),e={type:"error",message:"Out of memory, please refresh the site. (You must have loaded a LOT of images at once)"}}e&&postMessage(e)};self.onmessage=c;for(let a of n)c(a);n.length=0};var t;t=self.location.href;var u="",v,y;
try{u=(new URL(".",t)).href}catch{}y=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)};v=async b=>{b=await fetch(b,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);};var z=console.error.bind(console),A=!1;
function B(){if(!C?.buffer?.resizable){var b=E.buffer;C=new Int8Array(b);q=new Uint8Array(b);F=new Int32Array(b);r=new Uint32Array(b);G=new Float64Array(b);H=new BigInt64Array(b)}}function I(b){b=`Aborted(${b})`;z(b);A=!0;throw new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");}var J;async function K(b){try{var c=await v(b);return new Uint8Array(c)}catch{}if(y)b=y(b);else throw"both async and sync fetching of the wasm failed";return b}
async function L(b,c){try{var g=await K(b);return await WebAssembly.instantiate(g,c)}catch(h){z(`failed to asynchronously prepare wasm: ${h}`),I(h)}}async function M(b){var c=J;try{var g=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(g,b)}catch(h){z(`wasm streaming compile failed: ${h}`),z("falling back to ArrayBuffer instantiation")}return L(c,b)}class N{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}
var C,O={},Q=b=>{if(!A)try{b()}catch(c){if(!(c instanceof N||c=="unwind"))throw c;}finally{}},H,R=[],q,F,r,G,S={14568:(b,c)=>{var g=p.get(b);g&&(p.delete(b),postMessage({type:"needsInverse",src:g,inverse:c}))}},T,E,U={f:()=>I(""),c:()=>{},a:(b,c)=>{O[b]&&(clearTimeout(O[b].id),delete O[b]);if(!c)return 0;var g=setTimeout(()=>{delete O[b];Q(()=>T(b,performance.now()))},c);O[b]={id:g,U:c};return 0},e:function(b,c,g){if(!(b>=0&&b<=3))return 28;H[g>>3]=BigInt(Math.round((b===0?Date.now():performance.now())*
1E3*1E3));return 0},g:(b,c,g)=>{R.length=0;for(var h;h=q[c++];){var f=h!=105;f&=h!=112;g+=f&&g%8?4:0;R.push(h==112?r[g>>2]:h==106?H[g>>3]:h==105?F[g>>2]:G[g>>3]);g+=f?8:4}return S[b](...R)},d:b=>{var c=q.length;b>>>=0;if(b>2147483648)return!1;for(var g=1;g<=4;g*=2){a:{var h=(Math.min(2147483648,Math.ceil(Math.max(b,c+50331648/g)/65536)*65536)-E.buffer.byteLength+65535)/65536|0;try{E.grow(h);B();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},b:b=>{throw new N(b);}},V;
(async function(){var b={a:U};J??=u+"usytrace.wasm";b=V=(await M(b)).instance.exports;d._create_buffer=b.j;d._setCurrent=b.k;d._addImage=b.l;d._removeImage=b.m;d._historyStatus=b.n;d._trace=b.o;d._undo=b.p;d._redo=b.q;d._clear=b.r;d._point=b.s;d._autoTrace=b.t;d._eraseRegion=b.u;d._smoothTrace=b.v;d._offsetTrace=b.w;d._exportTrace=b.x;d._snap=b.y;d._getPixelColour=b.z;d._getCurrentPath=b.A;T=b.B;E=b.h;B();return V})().then(()=>{A||(V.i(),d.onRuntimeInitialized?.())});
