var c;c||=typeof Module != 'undefined' ? Module : {};const l=[];self.onmessage=a=>l.push(a);
c.onRuntimeInitialized=()=>{const a=TextDecoder.prototype.decode.bind(new TextDecoder("utf-8"));var d=b=>(...f)=>{f=b(...f);return a(new Uint8Array(m.buffer,n[f/4],n[f/4+1]))};const g=new Map,e={C:c._create_buffer,M:b=>c._setCurrent(g.get(b)),A:(b,f,k,q)=>g.set(b,c._addImage(f,k,q)),L:b=>{c._removeImage(g.get(b));g.delete(b)},H:c._historyStatus,O:d(c._trace),J:d(c._point),P:d(c._undo),K:d(c._redo),F:d(c._eraseRegion),smooth:d(c._smoothTrace),clear:c._clear,B:d(c._autoTrace),G:d(c._exportTrace),N:c._snap,
I:c._getPixelColour,D:d(c._getCurrentPath)},h=(b,f)=>{b.svg=f;return b},B={setCurrent:({src:b})=>e.M(b),removeImage:({src:b})=>e.L(b),setData:({src:b,type:f,width:k,height:q,data:K})=>{const A=e.C(parseInt(k,10),parseInt(q,10));m.set(K,A);e.A(b,A,parseInt(k,10),parseInt(q,10));return{src:b,type:f}},getHistoryStatus:b=>{const f=e.H();b.undo=!!((f&2)>>1);b.redo=!!(f&1);return b},clearTrace:b=>h(b,e.clear()),undoTrace:b=>h(b,e.P()),redoTrace:b=>h(b,e.K()),eraseRegion:b=>h(b,e.F(parseInt(b.begin,10),
parseInt(b.end,10))),smoothTrace:b=>h(b,e.smooth()),exportTrace:b=>{b["export"]=e.G(parseInt(b.PPO,10),"tab"===b.delim?1:0,parseFloat(b.lowFR),parseFloat(b.highFR),parseFloat(b.SPL.top),parseFloat(b.SPL.topPixel),parseFloat(b.SPL.bottom),parseFloat(b.SPL.bottomPixel),parseFloat(b.FR.top),parseFloat(b.FR.topPixel),parseFloat(b.FR.bottom),parseFloat(b.FR.bottomPixel));return b},addPoint:b=>h(b,e.J(parseInt(b.x,10),parseInt(b.y,10))),autoTrace:b=>h(b,e.B(parseInt(b.colourTolerance,10))),trace:b=>h(b,
e.O(parseInt(b.x,10),parseInt(b.y,10),parseInt(b.colourTolerance,10))),snapLine:b=>{b.line.position=e.N(parseInt(b.line.position,10),"x"===b.line.direction?1:0,parseInt(b.direction,10));return b},getPixelColour:b=>{const f=e.I(parseInt(b.x,10),parseInt(b.y,10));b.pixelColour=`${f>>16}, ${f>>8&255}, ${f&255}`;return b},getCurrentPath:b=>h(b,e.D())};d=({data:b})=>{let f;try{f=B[b.type](b)}catch(k){console.error(k.message),f={type:"error",message:"Out of memory, please refresh the site. (You must have loaded a LOT of images at once)"}}f&&
postMessage(f)};self.onmessage=d;for(const b of l)d(b);l.length=0};var p;p=self.location.href;var r="",t,u;try{r=(new URL(".",p)).href}catch{}u=a=>{var d=new XMLHttpRequest;d.open("GET",a,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)};t=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var v=console.error.bind(console),w=!1,m,n;
function x(){var a=y.buffer;new Int8Array(a);new Int16Array(a);m=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);n=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function z(a){a="Aborted("+a+")";v(a);w=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var C;
async function D(a){try{var d=await t(a);return new Uint8Array(d)}catch{}if(u)a=u(a);else throw"both async and sync fetching of the wasm failed";return a}async function E(a,d){try{var g=await D(a);return await WebAssembly.instantiate(g,d)}catch(e){v(`failed to asynchronously prepare wasm: ${e}`),z(e)}}
async function F(a){var d=C;try{var g=fetch(d,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(g,a)}catch(e){v(`wasm streaming compile failed: ${e}`),v("falling back to ArrayBuffer instantiation")}return E(d,a)}class G{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var H=0,I=null,J={},L=a=>{if(!w)try{a()}catch(d){if(!(d instanceof G||"unwind"==d))throw d;}},M,y,N={e:()=>z(""),b:()=>{},c:(a,d)=>{J[a]&&(clearTimeout(J[a].id),delete J[a]);if(!d)return 0;var g=setTimeout(()=>{delete J[a];L(()=>M(a,performance.now()))},d);J[a]={id:g,R:d};return 0},d:a=>{var d=m.length;a>>>=0;if(2147483648<a)return!1;for(var g=1;4>=g;g*=2){a:{var e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d+50331648/g)/65536))-y.buffer.byteLength+65535)/65536|0;try{y.grow(e);x();var h=1;break a}catch(B){}h=
void 0}if(h)return!0}return!1},a:a=>{throw new G(a);}};function O(){0<H?I=O:0<H?I=O:(c.calledRun=!0,w||(P.g(),c.onRuntimeInitialized?.()))}var P;
(async function(){H++;var a={a:N};C??=r+"usytrace.wasm";a=P=(await F(a)).instance.exports;c._create_buffer=a.h;c._setCurrent=a.i;c._addImage=a.j;c._removeImage=a.k;c._historyStatus=a.l;c._trace=a.m;c._undo=a.n;c._redo=a.o;c._clear=a.p;c._point=a.q;c._autoTrace=a.r;c._eraseRegion=a.s;c._smoothTrace=a.t;c._exportTrace=a.u;c._snap=a.v;c._getPixelColour=a.w;c._getCurrentPath=a.x;M=a.y;y=a.f;x();H--;0==H&&I&&(a=I,I=null,a());return P})();O();
